### ISSUE TITLE
Limit on 30 files??

### ISSUE THREAD

**Issue by TechnoX** [3MUl0R/mreAudioKit#1]
I've been using your amazing MRE for a couple events in Altspace and have been happy so far! Great work! 

But I've noticed a limit on 30 files. It just imports the first 30 files from Dropbox. I have tried different folders and files with different names, but it takes only the first 30 in alphabetical order. Tried to look through your code if it was a limit set somewhere, but couldn't find it. Maybe it is a limit in the dropbox API? 

Something you can update in the near future?

Thanks in advance!

**Comment by 3MUl0R** [comment]
I'm looking into it now.  My first guess is that dropbox is only delivering one page of results.

**Comment by 3MUl0R** [comment]
Turns out the dropbox page only loads the first 30 files with the http request.  There are a couple of other methods I could use to get the links but they all seemed like they were going to take longer then I have at the moment.

So, I've implemented multi-folder importing.  You can now import as many shared folders as you like with each folder having up to 30 files in it.  There is a separate button to clear your playlist.

b8778f8eed4d365976e22abbcc7c029e4ac2aaf2

Cheers          ᕕ(⌐■_■)ᕗ ♪♬
